version: '3'

services:
  
  jenkins:
    build: .
    container_name: jenkins
    privileged: true
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
  
  sonarqube:
    image: sonarqube
    container_name: sonarqube
    ports:
      - 9000:9000
      - 9092:9092

  registry:
    image: registry
    container_name: registry
    restart: always
    ports:
      - 5000:5000
